# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20161007_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
    ]
