# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20161005_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
    ]
