# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_remove_like_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
