# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20160924_0744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='photo',
        ),
    ]
