# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
