# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
